### ISSUE TITLE
IIS 8.5 error on load

### ISSUE THREAD

**Issue by Dae1** [DeborahK/Angular2-GettingStarted#12]
After last round of upgrades to angular rc4 I get following error, when running your "APM - Final Updated" under IIS. Error is following:
```
System.import('app').catch(function(err){ console.error(err);  });

TypeError: Cannot read property 'NeverChecked' of undefined
	    at eval (node_modules/@angular/compiler/src/view_compiler/constants.js:48:112)
	    at Object.eval (node_modules/@angular/compiler/src/view_compiler/constants.js:52:2)
	    at eval (node_modules/@angular/compiler/src/view_compiler/constants.js:114:4)
	    at eval (node_modules/@angular/compiler/src/view_compiler/constants.js:115:3)
```

Running from "npm start" is working fine.

**Comment by Dae1** [comment]
It appears Chrome cached old versions of the @angular files as everything is working fine in IE. 
Apologies for the false alarm.
